# Analise Exploratoria 

In [2]:
import pandas as pd
distritos = pd.read_csv('distritos_sp.csv')
distritos

cod_ibge          distritos  renda      quota  escolaridade  idade  \
0          1          Água Rasa   1961  34.619999           7.6     32   
1         12  Alto de Pinheiros   4180  75.959999           8.4     33   
2         23         Anhanguera   1093   4.500000           5.8     23   
3         34         Aricanduva   1311  21.020000           6.8     27   
4         45        Artur Alvim   1248  15.910000           7.0     27   
..       ...                ...    ...        ...           ...    ...   
91        92      Vila Medeiros   1405  19.760000           6.8     27   
92        93      Vila Prudente   1755  32.080002           7.2     30   
93        94         Vila Sônia   2970  41.410000           7.4     27   
94        95       São Domingos   2047  23.510000           6.8     26   
95        96            Lajeado    775   8.490000           5.4     21   

    mortalidade    txcresc   causasext  favel     denspop  
0         13.86  -1.840000   52.980000   0.00  125.610001  
1          8.68  -2.520000   38.570000   0.69   57.560001  
2         15.36  18.120001   22.680000   0.00    8.570000  
3         18.43  -1.070000   76.220001   5.38  138.539993  
4         19.73  -1.400000   67.250000   4.11  167.399994  
..          ...        ...         ...    ...         ...  
91        15.43  -1.410000   77.980003   2.49  188.929993  
92        14.36  -2.550000   66.510002   7.43  101.440002  
93        16.76  -0.900000   74.680000  14.93   80.120003  
94        14.30   0.710000   62.349998   8.55   72.919998  
95        18.65   2.830000  103.320000   3.84  141.009995  

[96 rows x 11 columns]

In [3]:
#vou dropar as infor de cod_ibge e distritos
#O PCA funciona apenas com dados numericos
distritos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   cod_ibge      96 non-null     int64  
 1   distritos     96 non-null     object 
 2   renda         96 non-null     int64  
 3   quota         96 non-null     float64
 4   escolaridade  96 non-null     float64
 5   idade         96 non-null     int64  
 6   mortalidade   96 non-null     float64
 7   txcresc       96 non-null     float64
 8   causasext     96 non-null     float64
 9   favel         96 non-null     float64
 10  denspop       96 non-null     float64
dtypes: float64(7), int64(3), object(1)
memory usage: 8.4+ KB


### O PCA agrupa as variaveis em fatores com base em correlações
### por isso a ideia é construir uma matriz de correlação para entender
### o grau de correlação, idealmente deve ser alto

## Matriz de correlação

In [4]:
# para cosntruir uma matriz eu dropo as colunas que nao vou usar
# e já faço na mesma linha a correlacao 
variaveL_numerica = distritos.drop(['cod_ibge', 'distritos'], axis = 1)
variaveL_numerica.corr()

renda     quota  escolaridade     idade  mortalidade  \
renda         1.000000  0.920099      0.777332  0.732307    -0.519585   
quota         0.920099  1.000000      0.850455  0.832737    -0.520282   
escolaridade  0.777332  0.850455      1.000000  0.955825    -0.582601   
idade         0.732307  0.832737      0.955825  1.000000    -0.553758   
mortalidade  -0.519585 -0.520282     -0.582601 -0.553758     1.000000   
txcresc      -0.424711 -0.554767     -0.692968 -0.703237     0.346049   
causasext    -0.462516 -0.491020     -0.606621 -0.615073     0.422790   
favel        -0.146957 -0.243010     -0.432548 -0.499838     0.130877   
denspop      -0.019711  0.057374      0.157673  0.141469    -0.093018   

               txcresc  causasext     favel   denspop  
renda        -0.424711  -0.462516 -0.146957 -0.019711  
quota        -0.554767  -0.491020 -0.243010  0.057374  
escolaridade -0.692968  -0.606621 -0.432548  0.157673  
idade        -0.703237  -0.615073 -0.499838  0.141469  
mortalidade   0.346049   0.422790  0.130877 -0.093018  
txcresc       1.000000   0.234472  0.281853 -0.279084  
causasext     0.234472   1.000000  0.404447 -0.045281  
favel         0.281853   0.404447  1.000000 -0.106481  
denspop      -0.279084  -0.045281 -0.106481  1.000000

- Para confirmar se os dados estão se correlacionando bem eu uso a biblioteca fator_analyzer  ela ajuda a entender se os dados estão adequados
- então se correlação das variaveis forem baixo, a base não é adequada para aplicar o PCA

In [5]:
#Libs fatpr analyzer
!pip install Analyze
!pip install factor_analyzer

  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikit-learn 1.2.1 requires joblib>=1.1.1, but you have joblib 1.0.1 which is incompatible.


  Attempting uninstall: joblib
    Found existing installation: joblib 1.2.0
    Uninstalling joblib-1.2.0:
      Successfully uninstalled joblib-1.2.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.1.0 requires joblib~=1.0.1, but you have joblib 1.2.0 which is incompatible.



  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
  Attempting uninstall: joblib
    Found existing installation: joblib 1.0.1
    Uninstalling joblib-1.0.1:
      Successfully uninstalled joblib-1.0.1


### Para entender se os dados são bons para aplicar o PCA
### Irei aplicar algumas tecnicas com criterio de KMO e Teste de esfericidade de Bartlett
----------------------------------------------------------------------------------------------------------
## Criterio de KMO: 
### é uma estatística que indica a proporção
### da variância dos dados que pode ser considerada comum a todas as variáveis, ou
### seja, que pode ser atribuída a um fator comum. Quanto mais próximo de 1 melhor
### o resultado, ou seja, mais adequada é a amostra à aplicação da análise fatorial
----------------------------------------------------------------------------------------------------------
## Teste de esfericidade de Bartlett

### é um teste de hipótese com o intuito de checar se a matriz de correlação é diferente de uma matriz identidade
###  se baseando em 0 e 1, se as variaveis forem acima de 0 
### isso demostra que dentro da base analisando existe correlacao entre os dados 


### Criterio de KMO

In [6]:
from factor_analyzer.factor_analyzer import calculate_kmo

In [7]:
# instancio a biblioteca e faço a transformação para entender o kmo 
#tanto global como as variaveis, e existe uma regra que os dados deve ser acima de 0.5 
#só assim é considerado bom
kmo_variaveis, kmo = calculate_kmo(variaveL_numerica)

In [8]:
kmo_variaveis

array([0.77821831, 0.81941916, 0.8560973 , 0.81750459, 0.94677797,
       0.84146713, 0.89083164, 0.78871213, 0.63275248])

In [9]:
#quanto mais proximo de 1 é uma base boa para aplicar o PCA
#tanto o global como as variaveis estão acima 
kmo

0.833091424182929

###  Teste de esfericidade de Bartlett

In [10]:
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity

In [11]:
# seguindo a mesma logica acima, aqui eu tenho retorno de dois valores

qui_quadrado, pvalor= calculate_bartlett_sphericity(variaveL_numerica)

print(qui_quadrado)
print(pvalor)

748.1593126421548
5.607017481838534e-134


In [12]:
#chamo novamente a variavel para entender qual a escala dos numeros, 
#uma escala desproporcial afeta negativamente meu modelo 
# consigo identificar que a escala de numeros são diferentes para as variaveis 
# renda, escolaridade e taxcresc
variaveL_numerica

renda      quota  escolaridade  idade  mortalidade    txcresc   causasext  \
0    1961  34.619999           7.6     32        13.86  -1.840000   52.980000   
1    4180  75.959999           8.4     33         8.68  -2.520000   38.570000   
2    1093   4.500000           5.8     23        15.36  18.120001   22.680000   
3    1311  21.020000           6.8     27        18.43  -1.070000   76.220001   
4    1248  15.910000           7.0     27        19.73  -1.400000   67.250000   
..    ...        ...           ...    ...          ...        ...         ...   
91   1405  19.760000           6.8     27        15.43  -1.410000   77.980003   
92   1755  32.080002           7.2     30        14.36  -2.550000   66.510002   
93   2970  41.410000           7.4     27        16.76  -0.900000   74.680000   
94   2047  23.510000           6.8     26        14.30   0.710000   62.349998   
95    775   8.490000           5.4     21        18.65   2.830000  103.320000   

    favel     denspop  
0    0.00  125.610001  
1    0.69   57.560001  
2    0.00    8.570000  
3    5.38  138.539993  
4    4.11  167.399994  
..    ...         ...  
91   2.49  188.929993  
92   7.43  101.440002  
93  14.93   80.120003  
94   8.55   72.919998  
95   3.84  141.009995  

[96 rows x 9 columns]

# Executando o PCA com Standard Scaler
### essas variáveis não estão em uma mesma escala, algo que vai impactar negativamente no procedimento de PCA
### então eu aplico o Standard Scaler para balancear esses dados, devolvendo um array com dados padronizados

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
colunas_numericas = variaveL_numerica.columns
colunas_numericas

Index(['renda', 'quota', 'escolaridade', 'idade', 'mortalidade', 'txcresc',
       'causasext', 'favel', 'denspop'],
      dtype='object')

In [15]:
#instancio o StandardScaler e faço 
# a transformação com fit
padronizar= StandardScaler()
variaveis_numericas = padronizar.fit_transform(variaveL_numerica)
variaveis_numericas

array([[ 1.08502328e-01,  1.80715140e-01,  5.23096244e-01,
         1.05541274e+00, -4.29281808e-01, -5.38805723e-01,
        -7.80681293e-01, -7.56406323e-01,  5.21804668e-01],
       [ 2.40630528e+00,  1.98438577e+00,  1.32019516e+00,
         1.28464265e+00, -1.47188596e+00, -7.33574170e-01,
        -1.40197826e+00, -6.68425227e-01, -8.57183702e-01],
       [-7.90322801e-01, -1.13342509e+00, -1.27037668e+00,
        -1.00765651e+00, -1.27369371e-01,  5.17822174e+00,
        -2.08708641e+00, -7.56406323e-01, -1.84993379e+00],
       [-5.64581006e-01, -4.12654904e-01, -2.74002674e-01,
        -9.07368417e-02,  4.90544879e-01, -3.18259087e-01,
         2.21327218e-01, -7.04087705e-02,  7.83822446e-01],
       [-6.29818314e-01, -6.35605024e-01, -7.47280632e-02,
        -9.07368417e-02,  7.52202169e-01, -4.12779054e-01,
        -1.65420498e-01, -2.32344990e-01,  1.36865133e+00],
       [ 5.20636431e-01,  1.67189899e-01,  9.21645940e-01,
         8.26182822e-01, -1.48396254e+00, -6.247330

In [16]:
#pra visualizar melhor vou incluir em outr variavel
#junto com com as columas que eu separei acima

dados_padronizados = pd.DataFrame(variaveis_numericas,columns= colunas_numericas)
dados_padronizados 

renda     quota  escolaridade     idade  mortalidade   txcresc  \
0   0.108502  0.180715      0.523096  1.055413    -0.429282 -0.538806   
1   2.406305  1.984386      1.320195  1.284643    -1.471886 -0.733574   
2  -0.790323 -1.133425     -1.270377 -1.007657    -0.127369  5.178222   
3  -0.564581 -0.412655     -0.274003 -0.090737     0.490545 -0.318259   
4  -0.629818 -0.635605     -0.074728 -0.090737     0.752202 -0.412779   
..       ...       ...           ...       ...          ...       ...   
91 -0.467243 -0.467629     -0.274003 -0.090737    -0.113280 -0.415643   
92 -0.104813  0.069895      0.124547  0.596953    -0.328644 -0.742167   
93  1.153335  0.476964      0.323822 -0.090737     0.154416 -0.269567   
94  0.197556 -0.304016     -0.274003 -0.319967    -0.340721  0.191576   
95 -1.119616 -0.959341     -1.668926 -1.466116     0.534825  0.798795   

    causasext     favel   denspop  
0   -0.780681 -0.756406  0.521805  
1   -1.401978 -0.668425 -0.857184  
2   -2.087086 -0.756406 -1.849934  
3    0.221327 -0.070409  0.783822  
4   -0.165420 -0.232345  1.368651  
..        ...       ...       ...  
91   0.297211 -0.438909  1.804943  
92  -0.197326  0.190984  0.032016  
93   0.154929  1.147301 -0.400020  
94  -0.376687  0.333794 -0.545923  
95   1.389762 -0.266772  0.833875  

[96 rows x 9 columns]

In [17]:
from sklearn.decomposition import PCA

In [18]:
# para eu executar esse método e transformar os dados, eu vou precisar passar uma quantidade de fatores que eu quero criar com o PCA
# E a quantidade de fatores que eu vou criar, vai ser igual a quantidade de variáveis, 
#eu vou primeiro construir todos os fatores possíveis, que é um número máximo de variáveis que eu tenho no conjunto de dados.

In [19]:
# valor maximo é 9
n_fatores = dados_padronizados.shape[1]
n_fatores 

9

In [20]:
pca= PCA(n_components = n_fatores)
pca.fit(dados_padronizados)

PCA(n_components=9)

## Variância explicada pelos fatores

Vou aplicar o pca.explained_variance_ratio_ porque consegue me dar uma porcentagem de varianca explicada or cada um dos valores gerados pelo PCA

In [22]:
#primeiro resultado esta trazendo 55% de explkicacao dos dados 
# segundo 0.12% assim por diante
pca.explained_variance_ratio_

array([0.55067008, 0.1293709 , 0.11070601, 0.08045185, 0.05881136,
       0.04425824, 0.01440763, 0.00722961, 0.00409432])

In [48]:
# defino o nome dos fatores usando for para trazer de 1 a 9

fatores = [f'F{i+1}' for i in range(n_fatores)]
fatores

['F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9']

### Visualizandos as variaveis

In [61]:
import plotly.express as px
import numpy as np 

In [62]:
fig = px.bar(x= fatores, y = pca.explained_variance_ratio_, text = np.around(pca.explained_variance_ratio_, decimals =2),
            title = "Scren Plot")
fig.update_layout(yaxis ={'title': 'Porcentagem de variancas explicadas', 'tickfont': {'size': 15}},
                 xaxis = {'title': 'Fatores','tickfont': {'size': 15}}, 
                 title= {'font':{'size':25}})
fig.show()

## Variancia acumulada

In [63]:
variancia_acumulada= [sum(pca.explained_variance_ratio_[0:i+1]) for i in range (n_fatores)]
variancia_acumulada

[0.5506700772160412,
 0.6800409820794432,
 0.7907469955852214,
 0.8711988432249137,
 0.930010202543966,
 0.9742684414070405,
 0.9886760753033329,
 0.9959056848263387,
 1.0000000000000002]

In [64]:
fig = px.bar(x= fatores, y = variancia_acumulada, text = np.around(variancia_acumulada, decimals =2),
            title = "Scren Plot")
fig.update_layout(yaxis ={'title': 'Porcentagem de variancas explicadas', 'tickfont': {'size': 15}},
                 xaxis = {'title': 'Fatores','tickfont': {'size': 15}}, 
                 title= {'font':{'size':25}})
fig.show()

### Aqui consigo analisar que o PCA funcionou de maneira eficaz porque com 2 ou 3 fatores eu consigo explicar a base